//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Authorship = new HashSet<Authorship>();
            this.BookEdition = new HashSet<BookEdition>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int GenreId { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Authorship> Authorship { get; set; }
        public virtual ICollection<BookEdition> BookEdition { get; set; }
    }
}
