//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Book = new HashSet<Book>();
            this.Magazine = new HashSet<Magazine>();
            this.Game = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
        public virtual ICollection<Magazine> Magazine { get; set; }
        public virtual ICollection<Game> Game { get; set; }
    }
}
