//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        public Reader()
        {
            this.Debt = 0m;
            this.Borrowing = new HashSet<Borrowing>();
            this.Reservation = new HashSet<Reservation>();
            this.Application = new HashSet<ReaderApplication>();
        }
    
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public string ApartmentNumber { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public decimal Debt { get; set; }
    
        public virtual ICollection<Borrowing> Borrowing { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
        public virtual ICollection<ReaderApplication> Application { get; set; }
        public virtual User User { get; set; }
    }
}
