//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Type = "C";
            this.Borrowing = new HashSet<Borrowing>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string E_Mail { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Borrowing> Borrowing { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
